### ISSUE TITLE
Fix websocket remote endpoint

### ISSUE THREAD

**Issue by esseks** [BitsDevelopmentTeam/bits-chrome-legacy#1]
As stated in the title, WS endpoint must be updated to take into account our new setup (WS/HTTP on port 80, so that it works in networks blocking other ports).

**Comment by thypon** [comment]
Do you mean the server side code to do that is ready?

**Comment by esseks** [comment]
Yes, the new server handles WS and HTTP on the same port. Defer this change until it enters production.
